<?php

	namespace Traineratwot\PDOExtended;

	use PDOStatement;

	class PDOEStatement extends PDOStatement
	{
		private $connection;

		public function __construct(PDOE $connection)
		{
			$this->connection = $connection;
		}

		public function execute($input_parameters = NULL)
		{
			$this->connection->queryCountIncrement();
			return parent::execute($input_parameters); // TODO: Change the autogenerated stub
		}
	}