<?php

	namespace Traineratwot\PDOExtended;

	use PDOStatement;

	class PDOEStatement extends PDOStatement
	{
		private $connection;

		/**
		 * @param PDOE $connection
		 */
		private function __construct(PDOE $connection)
		{
			$this->connection = $connection;
		}

		/**
		 * @inheritDoc
		 * @param $input_parameters
		 * @return bool
		 */
		public function execute($input_parameters = NULL)
		{
			$this->connection->queryCountIncrement();
			return parent::execute($input_parameters); // TODO: Change the autogenerated stub
		}
	}